excludeApplicationEvents: true
run:
  someFacet:
    # Disables the facet
    disabled: true
  spark_properties:
    disabled: false
    # Ignores verification the following of facet properties
    ignoredProperties: ['spark.master']
  parent:
    ignoredProperties: ['run']
job:
  someFacet:
    disabled: true
  someOtherFacet:
    disabled: true
dataset:
  version:
    ignoredProperties: [ 'datasetVersion' ]
outputDataset:
  someFacet:
    disabled: true